=== Roll20/roll20-api-scripts/_Example Script - Check for formatting details/script.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "script.json",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the script as it will appear on Roll20.",
            "type": "string"
        },
        "script": {
            "description": "The name of the JavaScript file, which must remain uniform throughout versions.",
            "type": "string"
        },
        "version": {
            "description": "The current version number of the script.",
            "type": "string"
        },
        "previousversions": {
            "description": "All previous versions of the script in an array format.",
            "type": "array",
            "items": {
                "description": "Previous version of the script.",
                "type": "string"
            },
            "uniqueItems": true
        },
        "description": {
            "description": "A short explanation of the script and it's use that will appear along side the script on Roll20.",
            "type": "string"
        },
        "authors": {
            "description": "A simple string telling who contributed toward the script.",
            "type": "string"
        },
        "roll20userid": {
            "description": "A simple string telling the Roll20 User ID's of the authors. Used internally and won't be shown publicly on the site.",
            "type": "string"
        },
        "useroptions": {
            "description": "An array of hashes that allow script authors to set pre-determined options for users to customize the functionality of the script.",
            "type": "array",
            "items": {
                "description": "Hash that allow script authors to set pre-determined an option for users to customize the functionality of the script.",
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [ "text", "number", "select", "checkbox" ]
                    },
                    "default": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                }
            },
            "uniqueItems": true
        },
        "dependencies": {
            "description": "A list of other scripts this script requires to function.",
            "type": "array",
            "items": {
                "description": "Another script this script requires to function.",
                "type": "string"
            },
            "uniqueItems": true
        },
        "modifies": {
            "description": "A list of the common Roll20 objects and properties the script reads and writes to.",
            "type": "object",
            "additionalProperties" : {
                "description": "A common Roll20 object or property the script reads and/or writes to.",
                "type": "string",
                "enum": [ "read", "write", "read,write" ]
            }
        },
        "conflicts": {
            "description": "A list of other scripts this script is known to conflict with.",
            "type": "array",
            "items": {
                "description": "Anther script this script is known to conflict with.",
                "type": "string"
            }
        }
    },
    "required": [ "name", "script", "previousversions", "description", "authors", "roll20userid", "useroptions", "dependencies", "modifies", "conflicts" ]
}

=== Roll20/roll20-api-scripts/WildShapeResizer/script.json
{
    "name": "WildShapeResizer",
    "script": "WildShapeResizer.js",
    "version": "0.0.2",
    "previousversions": ["0.0.1"],
    "description": "A script to automatically resize a Rollable Table Token when a different side is chosen. It does this by repurposing the “weight” attribute of the Items in the Rollable Table. It was written with D&D Druid Wild Shape tokens in mind, but would work for any square rollable table tokens from which players will choose different sides.\nThe script listens to token:change events, looks for a table with the same name as the token, and updates the token size when the side changes, so no other configuration should be required.",
    "authors": "Erik O.",
    "roll20userid": "1828947",
    "useroptions": [],
    "dependencies": [],
    "modifies": {
        "token.width": "read,write",
        "token.height": "read,write"
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/ShareVision/script.json
{
    "name": "ShareVision",
    "script": "ShareVision.js",
    "version": "1.4",
    "previousversions": [],
    "description": "ShareVision allows you to share a token's sight with the whole party. Use the aura status marker to share normal vision and the overdrive status marker to share darkvision.",
    "authors": "Scott C.",
    "roll20userid": "459831",
    "useroptions": [],
    "dependencies": [],
    "modifies": {
        "state.ShareVision.version": "read,write",
        "token.statusmarker": "read,write"
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/Cypher Systems by Roll20 Companion/script.json
{
    "name": "Cypher Systems by Roll20 Companion",
    "script": "cypher_systems_by_roll20.js",
    "version": "1.1.0",
    "previousversions": ["1.001"],
    "description": "Designed for the \"Cypher Systems by Roll20\" character sheet. Enables application of stat costs, recovery rolls, and damage to characters and NPCs from the chat roll template.",
    "authors": "Natha",
    "roll20userid": "75857",
    "useroptions": [],
    "dependencies": [],
    "modifies": {},
    "conflicts": ["Natha's Numenera","Cypher System Sheet"]
}

=== Roll20/roll20-api-scripts/CombatMaster/2.40/script.json
{
	"name": "Combat Master",
	"version": "2.40",
	"description": "# Combat Master v2.40\r\r**Features:** The script provides management of combat, incuding rolling initiative(option to use GroupInitiative), stepping through a turnorder, adding or remove conditions(import/export lists), tracking the length of a condition, and options for using external calls to other APIs and Macros.\rtype `!cmaster --main` for launching the API, and select the `i` in the corner for help/more info.\n* Visit the [CombatMaster 2.0](https://app.roll20.net/forum/permalink/9441420/)-forum thread for discussions and updates on the script.\n* [Combat Master repo](https://github.com/vicberg/CombatMaster) is the location of the active development of the API, and can contain newer versions of the API than through the dropdown menu in Roll20. The sourcecode for the dropdown menu version can be found [here](https://github.com/Roll20/roll20-api-scripts/tree/master/CombatMaster)\n\nUntil Decemeber 2020, The Combat Master API installed through the API dropdown menu didn't work, but the issue have now been solved. v.2.22 and older versions of the API might use `!cmaster --help` for accessing the help menu, instead of the current `!cmaster --main`.",
	"authors": "Victor B",
	"roll20userid": "3135709",
	"useroptions": [],
	"dependencies": [],
	"script": "CombatMaster.js",
	"modifies": {
		"state.COMBATMASTER": "read,write"
	},
	"conflicts": [],
	"previousversions": [
		"2.38",
    "2.36",
    "2.34",
		"2.33",
		"2.32",
		"2.22"
	]
}

=== Roll20/roll20-api-scripts/TreatWounds/script.json
{
    "name": "Pathfinder 2 Treat Wounds",
    "script": "treatwounds.js",
    "version": "1.2",
    "previousversions": ["1.0","1.1"],
    "description": "Treat Wounds is designed for Pathfinder 2nd Edition and aids in performing a Medicine check to treat wounds allowing for the user to pass in the specific DC of the check they want to attempt as well as opt to attempt Risky Surgery (per the feat). As with the PF2 ruleset, total healing is doubled on a critical success and will deal damage to the selected target on a critical failure. The script also accounts for the critical success/failure system with regards to beating/missing the DC by 10 or more and modifying results on a nat 1 or 20.",
    "authors": "Mark S.",
    "roll20userid": "580967",
    "useroptions": [
        {
            "name": "Show notes in rolls",
            "type": "checkbox",
            "description": "Select this option to show Medicine Skill Notes in rolls. This applies only to Treat Wounds API calls and will not override/affect the global sheet option for showing notes in rolls.",
            "value": "showMedNotes"
        }
    ],
    "dependencies": [],
    "modifies": {
        "character.controlledby": "read",
        "character.name": "read",
        "graphic.represents": "read"
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/DrD2StatusMarkers/script.json
{
    "name": "DrD2StatusMarkers",
    "script": "DrD2StatusMarkers.js",
    "version": "0.1.5",
    "previousversions": ["0.1.0", "0.1.1", "0.1.2", "0.1.3", "0.1.4"],
    "description": "Designed for use only with the Draci Doupe II sheet.\n\nThis script sets token markers based on relevant sheet attributes.\nWorks with the DrD2 token marker set, icons must be named `RED`, `BLU`, `GRN`, `VIO`, `BLK`, `GRY`, `load` followed by corresponding values.\nYou can download the token marker set [here](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fnesuprachy%2Froll20-character-sheets%2Ftree%2FDraci-doupe-II%2FDraci%2520doupe%2520II%2Fassets%2FDrD2-token_markers).",
    "authors": "nesuprachy",
    "roll20userid": "11071738",
    "useroptions": [],
    "dependencies": ["TokenMod"],
    "modifies": {
        "attribute.current": "read,write",
        "attribute.characterid": "read"
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/COGCrew/script.json
{
  "name": "COGCrew",
  "script": "COGCrew.js",
  "version": "1.00",
  "previousversions": [],
  "description": "Automatically updates the crew modifiers on starships and mecha sheets for the Chroniques Oubliees Galactiques french RPG.",
  "authors": "stephaned68",
  "roll20userid": "84776",
  "useroptions": [],
  "dependencies": [],
  "modifies": {
    "character.name": "read",
    "character.gmnotes": "read,write",
    "attribute.name": "read",
    "attribute.current": "read"
  },
  "conflicts": []
}

=== Roll20/roll20-api-scripts/MagicMaster/script.json
{
    "$schema": "https://github.com/DameryDad/roll20-api-scripts/blob/MagicMaster/MagicMaster/Script.json",
    "name": "MagicMaster",
    "script": "MagicMaster.js",
    "version": "3.5.0",
    "previousversions": ["2.044","2.045","2.046","2.048","3.051","1.3.00","1.3.01","1.3.02","1.3.03","1.4.01","1.4.02","1.4.04","1.4.05","1.4.06","1.4.07","1.5.01","1.5.02","1.5.03","2.1.0","2.1.1","2.2.0","2.2.1","2.3.0","2.3.1","2.3.2","2.3.3","2.3.4","3.0.0","3.1.2","3.2.0","3.2.1","3.3.0","3.4.0"],
    "description": "The MagicMaster API provides functions to manage all types of magic, including:\n* Wizard & Priest spell use and effects;\n* Character, NPC & Monster Powers; \n* discovery, looting, use and cursing of Magic Items;\n\n[MagicMaster Documentation](https://wiki.roll20.net/Script:MagicMaster) \n### Installation\nLoading MagicMaster via One-Click also loads the rest of the RPGMaster series of APIs \n[RPGMaster Documentation](https://wiki.roll20.net/RPGMaster) \n### Getting Started\n1. Ensure the CommandMaster API is also installed\n2. Run the CommandMaster `!cmd --initialise` command and add the player macros created to the Macro Bar, then\n3. Select tokens and use the `Token Setup` macro bar button just created to add all relevant Action Buttons to the token(s) (plus set the tokens/Characters up in any other way provided in the menu displayed)\n\n### Use In Play\nOnce the Getting Started steps have been done, the players and DM can then use the buttons displayed at the top of the screen when their character's token is selected to perform all actions needed in normal play.",
    "authors": "Richard E.",
    "roll20userid": "6497708",
    "useroptions": [],
    "dependencies": ["ChatSetAttr","Tokenmod","RoundMaster","RPGMaster library AD+D2e","InitMaster","AttackMaster"],
    "modifies": {
        "state.MagicMaster": "read,write",
		"player.online": "read",
		"character.id": "read",
		"character.name": "read",
		"character.controlledby": "read",
        "token.bar1_link": "read",
        "token.bar2_link": "read",
        "token.bar3_link": "read",
        "token.bar1_value": "read,write",
        "token.bar2_value": "read,write",
        "token.bar3_value": "read,write",
        "token.bar1_max": "read,write",
        "token.bar2_max": "read,write",
        "token.bar3_max": "read,write",
		"token.id": "read",
		"token.pageid": "read",
		"token.represents": "read",
		"token.name": "read",
		"token.aura2_radius": "read,write",
		"token.aura2_color": "read,write",
		"token.aura2_square": "read,write",
		"attribute.id": "read",
		"attribute.characterid": "read",
		"attribute.name": "read,write",
		"attribute.current": "read,write",
		"attribute.max": "read,write",
		"ability.id": "read",
		"ability.characterid": "read",
		"ability.name": "read,write",
		"ability.action": "read",
		"handout.id": "read,write",
		"handout.name": "read,write",
		"handout.notes": "write",
		"handout.inplayerjournals": "write"
    },
    "conflicts": []
}
