=== Roll20/roll20-api-scripts/_Example Script - Check for formatting details/script.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "script.json",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the script as it will appear on Roll20.",
            "type": "string"
        },
        "script": {
            "description": "The name of the JavaScript file, which must remain uniform throughout versions.",
            "type": "string"
        },
        "version": {
            "description": "The current version number of the script.",
            "type": "string"
        },
        "previousversions": {
            "description": "All previous versions of the script in an array format.",
            "type": "array",
            "items": {
                "description": "Previous version of the script.",
                "type": "string"
            },
            "uniqueItems": true
        },
        "description": {
            "description": "A short explanation of the script and it's use that will appear along side the script on Roll20.",
            "type": "string"
        },
        "authors": {
            "description": "A simple string telling who contributed toward the script.",
            "type": "string"
        },
        "roll20userid": {
            "description": "A simple string telling the Roll20 User ID's of the authors. Used internally and won't be shown publicly on the site.",
            "type": "string"
        },
        "useroptions": {
            "description": "An array of hashes that allow script authors to set pre-determined options for users to customize the functionality of the script.",
            "type": "array",
            "items": {
                "description": "Hash that allow script authors to set pre-determined an option for users to customize the functionality of the script.",
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [ "text", "number", "select", "checkbox" ]
                    },
                    "default": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                }
            },
            "uniqueItems": true
        },
        "dependencies": {
            "description": "A list of other scripts this script requires to function.",
            "type": "array",
            "items": {
                "description": "Another script this script requires to function.",
                "type": "string"
            },
            "uniqueItems": true
        },
        "modifies": {
            "description": "A list of the common Roll20 objects and properties the script reads and writes to.",
            "type": "object",
            "additionalProperties" : {
                "description": "A common Roll20 object or property the script reads and/or writes to.",
                "type": "string",
                "enum": [ "read", "write", "read,write" ]
            }
        },
        "conflicts": {
            "description": "A list of other scripts this script is known to conflict with.",
            "type": "array",
            "items": {
                "description": "Anther script this script is known to conflict with.",
                "type": "string"
            }
        }
    },
    "required": [ "name", "script", "previousversions", "description", "authors", "roll20userid", "useroptions", "dependencies", "modifies", "conflicts" ]
}

=== Roll20/roll20-api-scripts/Deal-Init/script.json
{
"name": "DealInit",
"script":"Deal-Init.js",	
"version": "1.3",
"previousversions": [ 
    "1.2"
],
"description": "Handles Savage Worlds card-based Inititive by dealing cards to Turn Order, automatically handling Jokers and Initiative Edges and sorting Turn Order by suit.",
"authors": "Pat Elwer",
"roll20userid": "8948",
"useroptions": [
    {
      "name": "Use Initiative Deck with 4 Jokers",
      "type": "checkbox",
      "description": "Select this option to add 2 extra Jokers to your Initiative Deck.",
      "value": "use4Jokers"
    }
  ],
"dependencies": [],
"modifies": {
	"character.": "read",
	"token.*": "read",
	"turnorder.*": "read,write"
	},
"conflicts":[]
}

=== Roll20/roll20-api-scripts/RollableTableMacros/script.json
{
  "name": "Rollable Table Macros",
	"script": "RollableTableMacros.js",
	"version": "1.1",
	"previousversions": ["1.0"],
	"description": "# Rollable Table Macros\r\rThis is a simple script that gets an item from a rollable table and enters its name as a chat message rather than showing it as a rollable table result. This allows use of most of the normal features of text chat such as dice rolls, inline rolls, macros, etc. A notable exception is roll queries, which aren't currently supported.\r\rThis will select an item at random from the table, respecting each item's weight. The item's icon, if any, is ignored.\r\r### How to\r\rSimply type `!rtm table-name`. The table name is not case-sensitive. If there are multiple tables with the same name, it will use the first one. If no table by that name is found, or no items are on that table, an error will be output to chat.\r\rYou can include a third paramater in the format `!rtm table-name Sender Name`. This will set the message's 'Speaking As' to whatever string is included after `table-name`.\r\r`!rtm table-name myself` will set the sender of the message to the player who typed in the API command.\r\rIf no third paramater is included, 'Speaking As' will be the formatted name of the table (example: *wild-magic-surge* becomes *Wild Magic Surge*).\r\r#### To do:\r\r* Handle text chat errors (for example, attempting to /w to a wrong name does not output anything)\r* Handle roll queries",
	"authors": "Nathanael W.",
	"roll20userid": "880239",
	"useroptions": [],
	"dependencies": [],
	"modifies": {},
	"conflicts": []
}

=== Roll20/roll20-api-scripts/13th Age Official Character Sheet Companion/script.json
{
    "name": "13th Age Official Character Sheet Companion",
    "script": "13th Age Official Character Sheet Companion.js",
    "version": "1.0",
    "previousversions": [],
    "description": "Enhances the Official 13th Age Character Sheet with quick Escalation Die tracking, automatic recovery tracking, token setup, and automatic staggered and down icons.\r\r**API COMMANDS**\r\r**!edie** will add the Escalation Die if there isn't one already in the scene. It will be placed at the top of the turn order. It will continue to count above 6 however it will never add more than a 6 bonus to roll attached to the character sheet. The associated character sheet stat is @{E-DIE} for use in personal macros or @{tracker|Escalation Die} for global macros. Note that the tracker attribute doesn't cap the result at 6 and can return a higher value.\r**!setup** will attempt to set up the bars of every token on the current page that represents a character. A token must already be set to represent a character for **!setup** to work. Bar1 is Temp HP, Bar2 is Recoveries, and Bar3 is HP. Note that the token still needs to be saved once for the HP_max to calculate since it's a disabled attribute.\r**!stag** is on by default. It will automatically add a Staggered or Dead status icon to tokens that represent a character. Using the **!stag** command will toggle the automatic icons on and off.\r**!rec** is on by default. It will automatically tick off a recovery each time to the rollbutton is used. Using the **!rec** command will toggle the automatic recovery tracking on and off.",
    "authors": "Steve K.",
    "roll20userid": "5047",
    "useroptions": [],
    "dependencies": [],
    "modifies": {},
    "conflicts": []
}

=== Roll20/roll20-api-scripts/Pathfinder Companion Neceros/script.json
{
	"name": "Pathfinder Companion Script",
	"script": "PFCompanion.js",
	"version": "1.01518021707",
	"previousversions": ["1.01511665715","1.0"],
	"description": "# Companion API Script v1.X\nThe Pathfinder Companion Script automates many of the day to day tasks of playing in and running a pathfinder game. The script is designed for the Neceros Pathfinder Sheet for Roll20. Below is the quick reference guide. For more in depth information on what the script can do, how to use it, and upcoming features read the [user's manual](https://docs.google.com/document/d/12OWJIiT8RWN6zeyZdpkl3d8_DY7XLVxbVL9QzxyJV_s/edit?usp=sharing) on google drive. For questions, suggestions, bug reports, or general comments drop by the [script's forum thread](https://app.roll20.net/forum/post/5412440/pf-pathfinder-companion-script-v1-dot-x-for-neceros-sheet/?pageforid=5412440#post-5412440).\n\nSheet compatibility: v1.6X [Neceros Pathfinder Sheet](https://app.roll20.net/forum/post/4735667/pf-pathfinder-sheet-thread-6/?pagenum=1)\n\n###Configuration Options\n- **Automatically create token actions for macro menus:** Enabling this will automatically create the indicated abilities for all PCs and NPCs as they are created or made into NPCs. Enabling the setting adds a menu where you can specify what menus should be created for all characters categorized by PC or NPC.\n- **Automatic Resource Tracking:** Will create handling for automatically tracking ammo for weapons and spell, ability, and item usages.\n- **Automatically handle HP changes:** Enabling this will autodeduct damage from temporary hp before affecting HP. It will also prevent healing from occurring beyond the max HP of a character.\n- **Maintain PC default tokens:** Enabling this option will bring up a table to set what attribute (by case insensitive name) each bar should link to and whether that bar should be visible to players or not. Having this option turned on will also update the default token of a character whenever there is a change made to that character (excluding movement and var value/max changes). NOTE: With this setting enabled, setting a token to represent a character will update the bar links and values to be synced appropriately. This will not be reflected in the token setup pop-up until you reload the menu. Exit the menu by hitting **CANCEL** (NOT **APPLY**) and your token will be set as the default token for that character and setup as per the settings in the config menu.\n- **Apply Condition/Buff statusmarkers:** Enabling this will apply the appropriate statusmarker to all tokens representing the buffed/conditioned character if that character is controlled by at least one player. You can designate statusmarkers to use for buffs on a per character basis by using the **!pfc --buffstatus** command while you have a single token selected or by passing a single character id after (e.g. **!pfc --buffstatus|@{Jord Strongbow|character_id}**). NOTE this setting will not work correctly unless Maintain PC default tokens is enabled\n###Current macro setup, auto attribute handling and command syntax:\n####Automatic Attribute Handling\n\n- **HP & Temp HP:** If this option is enabled in the config menu health deducted from a character's HP will be deducted from their temp hp first before being applied to their HP. Note this will not work with API applied HP changes (other than those caused by this script).\nMacro Setup\n\n- **Weapons:** Weapons can be setup to track ammo usage (according to # of attacks used, including usage of manyshot), other item usage, spell usage, ability usage, and custom attribute usage.\nAmmo Tracking: Setting the ammo field of a weapon to anything besides 1 tells the script that that weapon uses ammo. The script willgenerate the following field in the macro text of the weapon: ||ammo=?{Name of Ammunition Item}||. After the first time you answer this query, it will be replaced with your response.You can also manually put a different query in here to be prompted for what ammunition to use with each attack routine.\n- **Spell or Ability Tracking:** If a weapon is linked to a spell or ability (that has uses), an additional roll template field will be added to the macro that will display a button to outputthe spell card as well as buttons to increment, decrement, or custom adjust the number of spells used.\nSpells: A field similar to that for weapons linked to a spell will be added to all spells.\n- **Abilities:** A field similar to that for weapons linked to an ability will be added to all abilities that have uses.\ncustom attribute: Entering %%What you named the custom attribute%% into the description field (notes field for weapons) will cause the script to put a field similar to the spell or ability to allow you to adjust the quantity of it. This will only be created for those custom attributes that have a current/max comparison. This can also be used to add fields for spells,abilities, or items without having to directly edit the macro text.\nCommand syntax\n\n- **Item tracking:** !pfc --resource,item=Item Name,current=max OR +/-X OR X,max=+/-X OR X|characterid|characterid|...\n- **Ability tracking:** !pfc --resource,ability=Ability Name,current=max OR +/-X OR X|characterid|characterid|...\n- **Spell tracking:** !pfc --resource,spell=Spell Name,current=max OR +/-X OR X|characterid|characterid|...\n- **Custom Attribute tracking:** !pfc --resource,note=Custom Attribute Name,current=max OR +/-X OR X|characterid|characterid|...\n- **Whisper Adjusting:** !pfc --whisper,npc=public/private/swap,pc=public/private/swap,stats=public/private/swap|characerid|characterid|...\nAccess the Config Menu: !pfc --config\n- **Apply/Remove Buffs Conditions:** !pfc --apply,condition=all or part of a condtion name,buff=all or part of a buff name that has already been setup on the character,remove/swap|characterid|characterid|...\n- **Import Statblock:** !pfc --parse|characterid|characterid|characterid| OR !pfc --parse|{{statblock NEWCREATURE statblock NEW CREATURE ...}}\nCopy your statblock (pure text only - copy into a text editor first to clean off formatting) into the gmnotes of a fresh character or directly via chat, and then run the command. I have only tested the parser on pfsrd statblocks (and not many of those) so far, and hope to overcome the issues preventing multiple statblocks from being imported at once, as well as hopefully eventually allowing statblocks to be imported from chat.\nBuff statusmarker wizard: !pfc --buffstatus|characterid\nThe characterid is optional if you have a token representing a character selected. The command only works on a single character; having more than one token selected or passing more than one character id will only act on the first character in the list (this is unpredictable when using selected tokens).",
	"authors": "Scott C.",
	"roll20userid": "459831",
	"useroptions": [],
	"dependencies": [],
	"modifies": {
		"Characters": "read,write",
		"state.PFCompanion": "read,write",
		"tokens": "read,write",
		"character.defaulttoken": "read,write"
	},
	"conflicts": []
}

=== Roll20/roll20-api-scripts/DSA4_1-CritChecker/script.json
{
    "name": "DSA 4.1 Crit Checker",
    "script": "dsa41-crit-checker.js",
    "version": "1.0.0",
    "previousversions": [],
    "description": "This API Script checks for a critical success or failure of talent rolls in the DSA 4.1 Character Sheet (ie. 2 or more 1s or 20s in a roll). It is absolutely useless with any other Character Sheets",
    "authors": "Christian S.",
    "roll20userid": "6296398",
    "useroptions": [
    ],
    "dependencies": [],
    "modifies": {
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/DrD2LinkedTenacity/script.json
{
    "name": "DrD2LinkedTenacity",
    "script": "DrD2LinkedTenacity.js",
    "version": "0.1.0",
    "previousversions": [],
    "description": "Designed for use only with the Draci Doupe II sheet.\n\nThis script tracks changes made to the 'tenacity_current' attribute and propagates them to other sheets linked via the 'npc_owner' attribute.",
    "authors": "nesuprachy",
    "roll20userid": "11071738",
    "useroptions": [],
    "dependencies": ["ChatSetAttr"],
    "modifies": {
        "attribute.current": "read,write",
        "attribute.max": "read,write",
        "attribute.characterid": "read",
        "character.name": "read"
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/ConditionTracker/script.json
{
  "name": "Condition Tracker",
  "script": "ConditionTracker.js",
  "version": "1.1.0.beta-3.5",
  "previousversions": [],
  "description": "Track token conditions and custom effects as separate Roll20 Turn Tracker rows.",
  "authors": "MidNiteShadow7",
  "roll20userid": "16506286",
  "useroptions": [
    {
      "name": "gameSystem",
      "type": "select",
      "options": [
        "dnd5e",
        "dnd4e",
        "dnd35",
        "pathfinder1e",
        "pathfinder2e",
        "starfinder",
        "13thage",
        "sotdl",
        "cyphersystem",
        "dcc",
        "ose",
        "bfrpg",
        "knave",
        "intotheodd",
        "cairn",
        "wwn",
        "swn",
        "callofcthulhu",
        "deltagreen",
        "vaesen",
        "brp",
        "vtm",
        "wta",
        "mta",
        "htr",
        "ctd",
        "alienrpg",
        "mothership",
        "traveller",
        "cyberpunkred",
        "shadowrun",
        "genesys",
        "starwarsffg",
        "cortexprime",
        "gurps",
        "herosystem",
        "savageworlds",
        "wfrp4e",
        "wh40k",
        "whaos",
        "generic"
      ],
      "default": "dnd5e",
      "description": "Active game system. Determines the condition list and default status marker assignments. Changing this via --config gameSystem also resets markers to the new system's defaults. Default: dnd5e."
    },
    {
      "name": "useMarkers",
      "type": "checkbox",
      "value": "true",
      "checked": "checked",
      "description": "Apply Roll20 status markers to tokens when a condition is added. Default: enabled."
    },
    {
      "name": "useIcons",
      "type": "checkbox",
      "value": "true",
      "description": "Show short icon codes such as [G] instead of emoji in Turn Tracker rows. Default: disabled."
    },
    {
      "name": "subjectPromptBypass",
      "type": "checkbox",
      "value": "true",
      "description": "Skip the optional subject-token step for Spell, Ability, and Other effects. Default: disabled."
    },
    {
      "name": "suppressPublicChat",
      "type": "checkbox",
      "value": "true",
      "description": "Suppress all public chat announcements when conditions are applied or removed. GM whispers are unaffected. Default: disabled."
    },
    {
      "name": "enablePostApplyMacroButtons",
      "type": "checkbox",
      "value": "true",
      "description": "Show macro-creation buttons in the GM whisper after applying conditions, allowing one-click macro generation for repeated apply actions. Default: disabled."
    },
    {
      "name": "healthBar",
      "type": "select",
      "options": ["bar1_value", "bar2_value", "bar3_value"],
      "default": "bar1_value",
      "description": "Token bar to watch for 0 HP cleanup prompts. Default: bar1_value."
    },
    {
      "name": "language",
      "type": "select",
      "options": [
        "af",
        "ca",
        "zh-TW",
        "cs",
        "da",
        "nl",
        "en-US",
        "fi",
        "fr",
        "de",
        "el",
        "he",
        "hu",
        "it",
        "ja",
        "ko",
        "pl",
        "pt-PT",
        "pt-BR",
        "ru",
        "es",
        "sv",
        "tr",
        "uk"
      ],
      "default": "en-US",
      "description": "Output language for chat messages and the generated help handout. Supports Roll20 account languages; aliases en, zh, and pt are accepted in chat commands. Default: en-US."
    },
    {
      "name": "markerGrappled",
      "type": "text",
      "default": "grab",
      "description": "Status marker tag used for Grappled. Default: grab."
    },
    {
      "name": "markerRestrained",
      "type": "text",
      "default": "padlock",
      "description": "Status marker tag used for Restrained. Default: padlock."
    },
    {
      "name": "markerProne",
      "type": "text",
      "default": "back-pain",
      "description": "Status marker tag used for Prone. Default: back-pain."
    },
    {
      "name": "markerPoisoned",
      "type": "text",
      "default": "chemical-bolt",
      "description": "Status marker tag used for Poisoned. Default: chemical-bolt."
    },
    {
      "name": "markerStunned",
      "type": "text",
      "default": "pummeled",
      "description": "Status marker tag used for Stunned. Default: pummeled."
    },
    {
      "name": "markerBlinded",
      "type": "text",
      "default": "bleeding-eye",
      "description": "Status marker tag used for Blinded. Default: bleeding-eye."
    },
    {
      "name": "markerCharmed",
      "type": "text",
      "default": "chained-heart",
      "description": "Status marker tag used for Charmed. Default: chained-heart."
    },
    {
      "name": "markerFrightened",
      "type": "text",
      "default": "screaming",
      "description": "Status marker tag used for Frightened. Default: screaming."
    },
    {
      "name": "markerIncapacitated",
      "type": "text",
      "default": "interdiction",
      "description": "Status marker tag used for Incapacitated. Default: interdiction."
    },
    {
      "name": "markerInvisible",
      "type": "text",
      "default": "ninja-mask",
      "description": "Status marker tag used for Invisible. Default: ninja-mask."
    },
    {
      "name": "markerParalyzed",
      "type": "text",
      "default": "frozen-orb",
      "description": "Status marker tag used for Paralyzed. Default: frozen-orb."
    },
    {
      "name": "markerPetrified",
      "type": "text",
      "default": "fossil",
      "description": "Status marker tag used for Petrified. Default: fossil."
    },
    {
      "name": "markerUnconscious",
      "type": "text",
      "default": "sleepy",
      "description": "Status marker tag used for Unconscious. Default: sleepy."
    },
    {
      "name": "markerSpell",
      "type": "text",
      "default": "lightning-helix",
      "description": "Status marker tag used for Spell effects. Default: lightning-helix."
    },
    {
      "name": "markerAbility",
      "type": "text",
      "default": "fist",
      "description": "Status marker tag used for Ability effects. Default: fist."
    },
    {
      "name": "markerAdvantage",
      "type": "text",
      "default": "three-leaves",
      "description": "Status marker tag used for Advantage effects. Default: three-leaves."
    },
    {
      "name": "markerDisadvantage",
      "type": "text",
      "default": "broken-heart",
      "description": "Status marker tag used for Disadvantage effects. Default: broken-heart."
    }
  ],
  "dependencies": [],
  "modifies": {
    "Campaign.turnorder": "read,write",
    "Campaign.playerpageid": "read",
    "graphic._pageid": "read",
    "graphic.statusmarkers": "read,write",
    "graphic.bar1_value": "read",
    "graphic.bar2_value": "read",
    "graphic.bar3_value": "read",
    "graphic.layer": "read,write",
    "graphic.name": "read",
    "graphic.represents": "read",
    "graphic.controlledby": "read",
    "character.name": "read",
    "character.controlledby": "read",
    "attribute._characterid": "read",
    "attribute.name": "read,write",
    "attribute.current": "read,write",
    "macro.name": "read,write",
    "macro.playerid": "read,write",
    "macro.action": "write",
    "macro.visibleto": "write",
    "macro.istokenaction": "write",
    "handout.name": "read,write",
    "handout.notes": "write",
    "handout.inplayerjournals": "write",
    "handout.controlledby": "write",
    "player._id": "read",
    "player._displayname": "read"
  },
  "conflicts": []
}

=== Roll20/roll20-api-scripts/SwapTokenPositions/script.json
{
  "name": "SwapTokenPositions",
  "script": "SwapTokenPositions.js",
  "version": "2.1.0",
  "description": "Allows GMs and players to quickly swap the positions of two selected tokens on the same page using a staged FX pipeline (origin, travel, destination), presets, and persistent defaults.\r\n\r\nFor instructions see the *Help: SwapTokenPositions* Handout in game, or run `!swap-tokens --help` in game, or visit [SwapTokenPositions Forum Thread](https://app.roll20.net/forum/post/xxxxxxxx/swap-token-positions-api-script).",
  "authors": "MidNiteShadow7",
  "roll20userid": "16506286",
  "useroptions": [
    {
      "name": "origin-fx",
      "type": "select",
      "options": [
        "none",
        "nova-magic",
        "nova-acid",
        "nova-charm",
        "nova-fire",
        "nova-frost",
        "nova-holy",
        "nova-death",
        "burst-magic",
        "burst-acid",
        "burst-charm",
        "burst-fire",
        "burst-frost",
        "burst-holy",
        "burst-death",
        "burst-energy",
        "burst-smoke",
        "explode-magic",
        "explode-acid",
        "explode-charm",
        "explode-fire",
        "explode-frost",
        "explode-holy",
        "explode-death",
        "burn-magic",
        "burn-acid",
        "burn-charm",
        "burn-fire",
        "burn-frost",
        "burn-holy",
        "burn-death",
        "splatter-magic",
        "splatter-acid",
        "splatter-charm",
        "splatter-fire",
        "splatter-frost",
        "splatter-holy",
        "splatter-death",
        "splatter-dark",
        "glow-magic",
        "glow-acid",
        "glow-charm",
        "glow-fire",
        "glow-frost",
        "glow-holy",
        "glow-death"
      ],
      "default": "none",
      "description": "Point FX used at both origin positions before travel stage."
    },
    {
      "name": "travel-fx",
      "type": "select",
      "options": [
        "none",
        "beam-magic",
        "beam-acid",
        "beam-charm",
        "beam-fire",
        "beam-frost",
        "beam-holy",
        "beam-death",
        "beam-energy",
        "beam-lightning"
      ],
      "default": "none",
      "description": "Beam FX used during travel stage between the two positions."
    },
    {
      "name": "destination-fx",
      "type": "select",
      "options": [
        "none",
        "nova-magic",
        "nova-acid",
        "nova-charm",
        "nova-fire",
        "nova-frost",
        "nova-holy",
        "nova-death",
        "burst-magic",
        "burst-acid",
        "burst-charm",
        "burst-fire",
        "burst-frost",
        "burst-holy",
        "burst-death",
        "burst-energy",
        "burst-smoke",
        "explode-magic",
        "explode-acid",
        "explode-charm",
        "explode-fire",
        "explode-frost",
        "explode-holy",
        "explode-death",
        "burn-magic",
        "burn-acid",
        "burn-charm",
        "burn-fire",
        "burn-frost",
        "burn-holy",
        "burn-death",
        "splatter-magic",
        "splatter-acid",
        "splatter-charm",
        "splatter-fire",
        "splatter-frost",
        "splatter-holy",
        "splatter-death",
        "splatter-dark",
        "glow-magic",
        "glow-acid",
        "glow-charm",
        "glow-fire",
        "glow-frost",
        "glow-holy",
        "glow-death"
      ],
      "default": "none",
      "description": "Point FX used at both destination positions after swap."
    },
    {
      "name": "origin-time",
      "type": "number",
      "default": "0",
      "description": "Seconds to wait after origin FX before continuing (0-10)."
    },
    {
      "name": "travel-time",
      "type": "number",
      "default": "0",
      "description": "Travel animation duration in seconds (0-10)."
    },
    {
      "name": "travel-mode",
      "type": "select",
      "options": ["normal", "invisible"],
      "default": "normal",
      "description": "Controls whether tokens remain visible during travel stage."
    },
    {
      "name": "destination-time",
      "type": "number",
      "default": "0",
      "description": "Additional wait before destination FX is shown in seconds (0-10)."
    },
    {
      "name": "swap-delay",
      "type": "number",
      "default": "0",
      "description": "Additional delay between origin and travel stages in seconds (0-10)."
    },
    {
      "name": "destination-delay",
      "type": "number",
      "default": "0",
      "description": "Additional delay before destination FX is shown in seconds (0-10)."
    }
  ],
  "dependencies": [],
  "modifies": {
    "state.SwapTokenPositions": "read,write",
    "graphic.left": "read,write",
    "graphic.top": "read,write",
    "graphic.pageid": "read",
    "graphic.layer": "read,write",
    "graphic.name": "read",
    "graphic.subtype": "read",
    "Campaign.playerpageid": "read"
  },
  "conflicts": [],
  "previousversions": ["2.0.0", "1.0.0"]
}
