=== Roll20/roll20-api-scripts/_Example Script - Check for formatting details/script.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "script.json",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the script as it will appear on Roll20.",
            "type": "string"
        },
        "script": {
            "description": "The name of the JavaScript file, which must remain uniform throughout versions.",
            "type": "string"
        },
        "version": {
            "description": "The current version number of the script.",
            "type": "string"
        },
        "previousversions": {
            "description": "All previous versions of the script in an array format.",
            "type": "array",
            "items": {
                "description": "Previous version of the script.",
                "type": "string"
            },
            "uniqueItems": true
        },
        "description": {
            "description": "A short explanation of the script and it's use that will appear along side the script on Roll20.",
            "type": "string"
        },
        "authors": {
            "description": "A simple string telling who contributed toward the script.",
            "type": "string"
        },
        "roll20userid": {
            "description": "A simple string telling the Roll20 User ID's of the authors. Used internally and won't be shown publicly on the site.",
            "type": "string"
        },
        "useroptions": {
            "description": "An array of hashes that allow script authors to set pre-determined options for users to customize the functionality of the script.",
            "type": "array",
            "items": {
                "description": "Hash that allow script authors to set pre-determined an option for users to customize the functionality of the script.",
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [ "text", "number", "select", "checkbox" ]
                    },
                    "default": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                }
            },
            "uniqueItems": true
        },
        "dependencies": {
            "description": "A list of other scripts this script requires to function.",
            "type": "array",
            "items": {
                "description": "Another script this script requires to function.",
                "type": "string"
            },
            "uniqueItems": true
        },
        "modifies": {
            "description": "A list of the common Roll20 objects and properties the script reads and writes to.",
            "type": "object",
            "additionalProperties" : {
                "description": "A common Roll20 object or property the script reads and/or writes to.",
                "type": "string",
                "enum": [ "read", "write", "read,write" ]
            }
        },
        "conflicts": {
            "description": "A list of other scripts this script is known to conflict with.",
            "type": "array",
            "items": {
                "description": "Anther script this script is known to conflict with.",
                "type": "string"
            }
        }
    },
    "required": [ "name", "script", "previousversions", "description", "authors", "roll20userid", "useroptions", "dependencies", "modifies", "conflicts" ]
}

=== Roll20/roll20-api-scripts/DifficultyRating/script.json
{
    "name": "Difficulty Rating",
    "script": "DifficultyRating.js",
    "version": "1.04",
    "previousversions": ["1.03"],
    "description": "This script allows automatic difficulty calculation for 5th Edition D&D Encounters.  It is compatible with the OGL and 5e-Shaped scripts.",
    "authors": "M. Greene",
    "roll20userid": "1583758",
    "useroptions": [],
    "dependencies": [],
    "modifies": {
        "state.DifficultyRating": "read,write"
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/_Example Script - Check for formatting details/script.json
{
    "$schema": "https://github.com/Roll20/roll20-api-scripts/master/_Example%20Script%20-%20Check%20for%20formatting%20details/script.schema.json",
    "name": "Example",
    "script": "example.js",
    "version": "1.1",
    "previousversions": ["1.0","0.5"],
    "description": "This is an example package.json file in order to show the formatting and syntax required for the script to be deployed in Roll20. It is important for this section to be filled out in detail, as it's the primary way users will get information about the purpose and use of the script. Included in the description section needs to be an example use or purpose, list and explanation of API Commands, and any other information necessary to operating the script.",
    "authors": "Steve K.",
    "roll20userid": "5047",
    "useroptions": [
        {
            "name": "variable1", 
            "type": "text",
            "default": "Default Text",
            "description": "This is the first user option. Options will appear in the order they are placed inside the useroptions hash on their API page. This option is a text input that will accept any string."
        },
        {
            "name": "variable2", 
            "type": "number",
            "default": "1",
            "description": "The second user option is a number input and will only accept valid numbers."
        },
        {
            "name": "selectoption",
            "type": "select", 
            "options": ["one", "two", "three"],
            "default": "three",
            "description": "The third user option is a select, with both set options and a default option."
        },
        {
            "name": "variable3", 
            "type": "checkbox",
            "value": "borkborkbork",
            "checked" : "checked",
            "description": "The fourth user option is a checkbox with a value for the checked box as well as whether or not the box is checked by default."
        }
    ],
    "dependencies": ["Red","Flight"],
    "modifies": {
        "state.autoStaggered": "read,write",
        "state.autoRecovery": "read,write",
        "token.bar1_link": "read,write",
        "token.bar2_link": "read,write",
        "token.bar3_link": "read,write",
        "attribute.id": "read,write"
    },
    "conflicts": ["TokenMod", "Blue"]
}

=== Roll20/roll20-api-scripts/ScriptInfo/script.json
{
  "name": "ScriptInfo",
  "script": "ScriptInfo.js",
  "version": "0.0.3",
  "description": "# ScriptInfo \r\rScriptInfo helps you troubleshoot script errors or to get help with odd script behavior. ScriptInfo will give you a report of installed scripts and their versions, as well as what line each script starts on. \r\rThe version of a script is important if you need to ask for help regarding an unexpected or odd behavior, and lets the community or the script author verify you are on the correct version (or at least a version that should deliver the sort of behavior you expect). \r\rLine numbers are important because when your game's sandbox spins up, all of the scripts are collected into a single, long file of javascript code. If your sandbox errors out due to a problem with the execution of a script, it will report a line number. However, that line number will be between 1 and the total number of script lines in your game, so how do you know where that error originated? With ScriptInfo, you can run a different report to learn that an error on line X represents line Y of script Z. For a simple example, imagine you have 10 scripts installed (ScriptA, ScriptB, ScriptC, etc.), each consisting of 100 lines of code. You get an error that lists line #304 as where the error occurred. ScriptInfo would tell you that line #304 represents line 4 of ScriptD\r\r## Limitations \r\rScriptInfo interrogates a particular object in javascript that script authors must opt-in to use. If a script does not report to this object, ScriptInfo will not be able to get the information it needs, though it will still be able to tell you basic information (such as that an error occurred so-many-lines after a given script and/or so-many-lines before a given script). Many of the more widely used scripts available in the one-click do make use of this centralized reporting object, including TokenMod (as well as the rest of The Arcane Scriptomancer's scripts: RecursiveTables, GroupInit, etc.), ScriptCards, Reporter, Supernotes, Spawn, SmartAoE, and all of the metascripts.\r\r## Usage \r\rTo get the report of all scripts, use the command: \r\r!scriptinfo \r\rTo get a report of one or more lines, use the same handle, followed by the line numbers you wish to know about, each separated by a space: \r\r!scriptinfo 2549\r\r!scriptinfo 180 2021 15024\r\rTo get a report of the size of your state (broken out by each key), use: \r\r!stateinfo \r\rFor more information, see the original thread in the Mod Script forum:\r\r[ScriptInfo Forum Thread](https://app.roll20.net/forum/post/11309751/script-scriptinfo-reports-scripts-versions-and-locations-of-errors-to-help-you-troubleshoot-or-to-help-you-get-help/)",
  "authors": "timmaugh",
  "roll20userid": "5962076",
  "useroptions": [],
  "dependencies": [],
  "modifies": {},
  "conflicts": [],
  "previousversions": [
    "0.0.1",
    "0.0.2"
  ]
}

=== Roll20/roll20-api-scripts/Forbidden Lands Dice Roller/script.json
{
	"name": "Forbidden Lands Year-Zero Die Roller",
	"script": "FORLDieRoller.js",
	"version": "1.0",
	"previousversions": ["none"],
	"description": "This is a Die Roller used for Forbidden Lands dice rolls. It is used in combination with the Forbidden Lands Character Sheet (forthcoming in April 2018) but can be used independently of each other.  Note this is based on the current alpha rules and the core MYZ system; it is subject to change.",
	"authors": "Barry Snyder",
	"roll20userid": "399162",
	"useroptions": [],
	"dependencies": [],
	"modifies": {},
	"conflicts": []
}

=== Roll20/roll20-api-scripts/APISmartAttributes/script.json
{
  "name": "APISmartAttributes",
  "version": "0.0.1",
  "description": "APISmartAttributes provides an interface for managing beacon attributes in a slightly smarter way.",
  "authors": "GUD Team",
  "roll20userid": "",
  "dependencies": [],
  "modifies": {},
  "conflicts": [],
  "script": "APISmartAttributes.js",
  "useroptions": [],
  "previousversions": []
}

=== Roll20/roll20-api-scripts/Shadow of the Demon Lord/script.json
{
    "name": "Shadow of the Demon Lord",
    "script": "sotdl.js",
    "version": "0.2",
    "previousversions": ["0.1"],
    "description": "This takes the Shadow of the Demon Lord character sheet to the next level, since the core Game Mechanics requirements exceed what can be done with macros, such as detecting rolls totaling 20 or more.",
    "authors": "Matthew Paluch(170911)",
    "roll20userid": "170911",
    "useroptions": [
    ],
    "dependencies": [],
    "modifies": {
    	"state.DL": "read,write"
    },
    "conflicts": []
}

=== Roll20/roll20-api-scripts/EzExhaust2024/script.json
{
    "name": "Ez Exhaust 2024",
    "script": "EzExhaust2024.js",
    "version": "1.0",
    "previousversions": [],
    "description": "Provides GMs and Players with a simple method for applying, and managing Exhaustion within the 5E 2024 ruleset.",
    "authors": "Kahooty.",
    "roll20userid": "14337689",
    "useroptions": [],
    "dependencies": [],
    "modifies": {},
    "conflicts": []
}

=== Roll20/roll20-api-scripts/DeltaGreenRPGCompanion/script.json
{
    "name": "Delta Green Companion API",
    "script": "DG_companion.js",
    "version": "1.5",
    "previousversions": [],
    "description": "Enhances the Unofficial Delta Green Character Sheet with autocomputation of projection on bonds.",
    "authors": " Marco M.",
    "roll20userid": "3726",
    "useroptions": [],
    "dependencies": [],
    "modifies": {},
    "conflicts": []
}
